program KVKNet;

uses
  Forms,
  ServerModule in 'ServerModule.pas' {ServerMod: TUniGUIServerModule},
  MainModule in 'MainModule.pas' {MainMod: TUniGUIMainModule},
  Main in 'Main.pas' {MainForm: TUniForm},
  McMLib in 'Sistem\McMLib.pas',
  unPwdUtilities in 'Sistem\unPwdUtilities.pas',
  unLogin in 'Sistem\unLogin.pas' {frmLogin: TUniLoginForm},
  unSifreDegistir in 'Sistem\unSifreDegistir.pas' {frmSifreDegistir: TUniForm},
  unLicenceInfo in 'Sistem\unLicenceInfo.pas' {frmLicenceInfo: TUniForm},
  unDashboard in 'Sistem\unDashboard.pas' {frDashboard: TUniFrame},
  unKurumGrupTanim in 'Kurumsal\unKurumGrupTanim.pas' {frmKurumGrupTanim: TUniForm},
  unFirmaTanim in 'Kurumsal\unFirmaTanim.pas' {frmFirmaTanim: TUniForm},
  unFirmaSec in 'Kurumsal\unFirmaSec.pas' {frmFirmaSec: TUniForm},
  unDepartmanListe in 'Kurumsal\unDepartmanListe.pas' {frDepartmanListe: TUniFrame},
  unDepartmanTanim in 'Kurumsal\unDepartmanTanim.pas' {frmDepartmanTanim: TUniForm},
  unDepartmanSec in 'Kurumsal\unDepartmanSec.pas' {frmDepartmanSec: TUniForm},
  unRolListe in 'Kurumsal\unRolListe.pas' {frRolListe: TUniFrame},
  unRolTanim in 'Kurumsal\unRolTanim.pas' {frmRolTanim: TUniForm},
  unKullaniciListe in 'Kurumsal\unKullaniciListe.pas' {frKullaniciListe: TUniFrame},
  unRolKullaniciTurSec in 'Kurumsal\unRolKullaniciTurSec.pas' {frmRolKullaniciTurSec: TUniForm},
  unAyarlarListe in 'Kurumsal\unAyarlarListe.pas' {frAyarlarListe: TUniFrame},
  unAyarlarTanim in 'Kurumsal\unAyarlarTanim.pas' {frmAyarlarTanim: TUniForm},
  unKVKKSurecListe in 'Tanimlar\unKVKKSurecListe.pas' {frKVKKSurecListe: TUniFrame},
  unKVKKSurecTanim in 'Tanimlar\unKVKKSurecTanim.pas' {frmKVKKSurecTanim: TUniForm},
  unKVKKSurecSec in 'Tanimlar\unKVKKSurecSec.pas' {frmKVKKSurecSec: TUniForm},
  unKVKKKaynakListe in 'Tanimlar\unKVKKKaynakListe.pas' {frKVKKKaynakListe: TUniFrame},
  unKVKKKaynakTanim in 'Tanimlar\unKVKKKaynakTanim.pas' {frmKVKKKaynakTanim: TUniForm},
  unKVKKKaynakSec in 'Tanimlar\unKVKKKaynakSec.pas' {frmKVKKKaynakSec: TUniForm},
  unKVKKKategoriListe in 'Tanimlar\unKVKKKategoriListe.pas' {frKVKKKategoriListe: TUniFrame},
  unKVKKKategoriTanim in 'Tanimlar\unKVKKKategoriTanim.pas' {frmKVKKKategoriTanim: TUniForm},
  unKVKKKategoriSec in 'Tanimlar\unKVKKKategoriSec.pas' {frmKVKKKategoriSec: TUniForm},
  unKVKKVeriTipiListe in 'Tanimlar\unKVKKVeriTipiListe.pas' {frKVKKVeriTipiListe: TUniFrame},
  unKVKKVeriTipiTanim in 'Tanimlar\unKVKKVeriTipiTanim.pas' {frmKVKKVeriTipiTanim: TUniForm},
  unKVKKVeriTipiSec in 'Tanimlar\unKVKKVeriTipiSec.pas' {frmKVKKVeriTipiSec: TUniForm},
  unKVKKKisiListe in 'Tanimlar\unKVKKKisiListe.pas' {frKVKKKisiListe: TUniFrame},
  unKVKKKisiTanim in 'Tanimlar\unKVKKKisiTanim.pas' {frmKVKKKisiTanim: TUniForm},
  unKVKKKisiSec in 'Tanimlar\unKVKKKisiSec.pas' {frmKVKKKisiSec: TUniForm},
  unKVKKTarafListe in 'Tanimlar\unKVKKTarafListe.pas' {frKVKKTarafListe: TUniFrame},
  unKVKKTarafTanim in 'Tanimlar\unKVKKTarafTanim.pas' {frmKVKKTarafTanim: TUniForm},
  unKVKKTarafSec in 'Tanimlar\unKVKKTarafSec.pas' {frmKVKKTarafSec: TUniForm},
  unKVKKMetodListe in 'Tanimlar\unKVKKMetodListe.pas' {frKVKKMetodListe: TUniFrame},
  unKVKKMetodTanim in 'Tanimlar\unKVKKMetodTanim.pas' {frmKVKKMetodTanim: TUniForm},
  unKVKKMetodSec in 'Tanimlar\unKVKKMetodSec.pas' {frmKVKKMetodSec: TUniForm},
  unKVKKAmacListe in 'Tanimlar\unKVKKAmacListe.pas' {frKVKKAmacListe: TUniFrame},
  unKVKKAmacTanim in 'Tanimlar\unKVKKAmacTanim.pas' {frmKVKKAmacTanim: TUniForm},
  unKVKKAmacSec in 'Tanimlar\unKVKKAmacSec.pas' {frmKVKKAmacSec: TUniForm},
  unKVKKDayanakListe in 'Tanimlar\unKVKKDayanakListe.pas' {frKVKKDayanakListe: TUniFrame},
  unKVKKDayanakTanim in 'Tanimlar\unKVKKDayanakTanim.pas' {frmKVKKDayanakTanim: TUniForm},
  unKVKKDayanakSec in 'Tanimlar\unKVKKDayanakSec.pas' {frmKVKKDayanakSec: TUniForm},
  unKVKKOnemDereceListe in 'Tanimlar\unKVKKOnemDereceListe.pas' {frKVKKOnemDereceListe: TUniFrame},
  unKVKKOnemDereceTanim in 'Tanimlar\unKVKKOnemDereceTanim.pas' {frmKVKKOnemDereceTanim: TUniForm},
  unKVKKOnemDereceSec in 'Tanimlar\unKVKKOnemDereceSec.pas' {frmKVKKOnemDereceSec: TUniForm},
  unKVKKTedbirListe in 'Tanimlar\unKVKKTedbirListe.pas' {frKVKKTedbirListe: TUniFrame},
  unKVKKTedbirTanim in 'Tanimlar\unKVKKTedbirTanim.pas' {frmKVKKTedbirTanim: TUniForm},
  unKVKKTedbirSec in 'Tanimlar\unKVKKTedbirSec.pas' {frmKVKKTedbirSec: TUniForm},
  unKVKKKontrolSonucListe in 'Tanimlar\unKVKKKontrolSonucListe.pas' {frKVKKKontrolSonucListe: TUniFrame},
  unKVKKKontrolSonucTanim in 'Tanimlar\unKVKKKontrolSonucTanim.pas' {frmKVKKKontrolSonucTanim: TUniForm},
  unKVKKKontrolSonucSec in 'Tanimlar\unKVKKKontrolSonucSec.pas' {frmKVKKKontrolSonucSec: TUniForm},
  unKVKKDokumanTipListe in 'Tanimlar\unKVKKDokumanTipListe.pas' {frKVKKDokumanTipListe: TUniFrame},
  unKVKKDokumanTipTanim in 'Tanimlar\unKVKKDokumanTipTanim.pas' {frmKVKKDokumanTipTanim: TUniForm},
  unKVKKDokumanTipSec in 'Tanimlar\unKVKKDokumanTipSec.pas' {frmKVKKDokumanTipSec: TUniForm},
  unKVKKVeriDokumanListe in 'Tanimlar\unKVKKVeriDokumanListe.pas' {frKVKKVeriDokumanListe: TUniFrame},
  unKVKKVeriDokumanTanim in 'Tanimlar\unKVKKVeriDokumanTanim.pas' {frmKVKKVeriDokumanTanim: TUniForm},
  unKVKKVeriDokumanSec in 'Tanimlar\unKVKKVeriDokumanSec.pas' {frmKVKKVeriDokumanSec: TUniForm},
  unKVKKEkipmanListe in 'Tanimlar\unKVKKEkipmanListe.pas' {frKVKKEkipmanListe: TUniFrame},
  unKVKKEkipmanTanim in 'Tanimlar\unKVKKEkipmanTanim.pas' {frmKVKKEkipmanTanim: TUniForm},
  unKVKKEkipmanSec in 'Tanimlar\unKVKKEkipmanSec.pas' {frmKVKKEkipmanSec: TUniForm},
  unEnvanterListe2 in 'Formlar\unEnvanterListe2.pas' {frEnvanterListe2: TUniFrame},
  unEnvanterTanim2 in 'Formlar\unEnvanterTanim2.pas' {frmEnvanterTanim2: TUniForm},
  unCheckListListe in 'Formlar\unCheckListListe.pas' {frCheckListListe: TUniFrame},
  unCheckListTanim in 'Formlar\unCheckListTanim.pas' {frmCheckListTanim: TUniForm},
  unDetayEnvanterListe in 'Formlar\unDetayEnvanterListe.pas' {frDetayEnvanterListe: TUniFrame},
  unVSBasvuruListe in 'Formlar\unVSBasvuruListe.pas' {frVSBasvuruListe: TUniFrame},
  unVSBasvuruKayit in 'Formlar\unVSBasvuruKayit.pas' {frmVSBasvuruKayit: TUniForm},
  unVSBasvuruDokumanKayit in 'Formlar\unVSBasvuruDokumanKayit.pas' {frmVSBasvuruDokumanKayit: TUniForm},
  unVSDepartmanListe in 'Formlar\unVSDepartmanListe.pas' {frVSDepartmanListe: TUniFrame},
  unVSDepartmanKayit in 'Formlar\unVSDepartmanKayit.pas' {frmVSDepartmanKayit: TUniForm},
  unAydinlatmaSablonListe in 'Formlar\unAydinlatmaSablonListe.pas' {frAydinlatmaSablonListe: TUniFrame},
  unAydinlatmaSablonTanim in 'Formlar\unAydinlatmaSablonTanim.pas' {frmAydinlatmaSablonTanim: TUniForm},
  unAcikRizaKayitListe in 'Formlar\unAcikRizaKayitListe.pas' {frAcikRizaKayitListe: TUniFrame},
  unAcikRizaKayitTanim in 'Formlar\unAcikRizaKayitTanim.pas' {frmAcikRizaKayitTanim: TUniForm},
  unAcikRizaDokumanKayit in 'Formlar\unAcikRizaDokumanKayit.pas' {frmAcikRizaDokumanKayit: TUniForm},
  unAcikRizaVKDurum in 'Formlar\unAcikRizaVKDurum.pas' {frmAcikRizaVKDurum: TUniForm},
  unRptVKImhaRaporu in 'Raporlar\unRptVKImhaRaporu.pas' {frRptVKImhaRaporu: TUniFrame},
  unRptVKImhaGecmisi in 'Raporlar\unRptVKImhaGecmisi.pas' {frRptVKImhaGecmisi: TUniFrame},
  unRptRiskAnalizRaporu in 'Raporlar\unRptRiskAnalizRaporu.pas' {frRptRiskAnalizRaporu: TUniFrame},
  unUnvanListe in 'Kurumsal\unUnvanListe.pas' {frUnvanListe: TUniFrame},
  unUnvanTanim in 'Kurumsal\unUnvanTanim.pas' {frmUnvanTanim: TUniForm},
  unErisimYetkiListe in 'Formlar\unErisimYetkiListe.pas' {frErisimYetkiListe: TUniFrame},
  unErisimYetkiTanim in 'Formlar\unErisimYetkiTanim.pas' {frmErisimYetkiTanim: TUniForm},
  unRptYetkiMatrisi in 'Raporlar\unRptYetkiMatrisi.pas' {frRptYetkiMatrisi: TUniFrame},
  unDuyuruListe in 'Sistem\unDuyuruListe.pas' {frDuyuruListe: TUniFrame},
  unDuyuruTanim in 'Sistem\unDuyuruTanim.pas' {frmDuyuruTanim: TUniForm},
  unDuyuruDetay in 'Sistem\unDuyuruDetay.pas' {frmDuyuruDetay: TUniForm},
  unOzelOnaySablonListe in 'Formlar\unOzelOnaySablonListe.pas' {frOzelOnaySablonListe: TUniFrame},
  unOzelOnaySablonTanim in 'Formlar\unOzelOnaySablonTanim.pas' {frmOzelOnaySablonTanim: TUniForm},
  unOzelOnaySablonDosya in 'Formlar\unOzelOnaySablonDosya.pas' {frmOzelOnaySablonDosya: TUniForm},
  unOzelOnayKayitTanim in 'Formlar\unOzelOnayKayitTanim.pas' {frmOzelOnayKayitTanim: TUniForm},
  unParametreMCTanim in 'Kurumsal\unParametreMCTanim.pas' {frmParametreMCTanim: TUniForm},
  unHelpPage in 'Sistem\unHelpPage.pas' {frmHelpPage: TUniForm},
  unHelpTanim in 'Sistem\unHelpTanim.pas' {frmHelpTanim: TUniForm},
  unHelpListe in 'Sistem\unHelpListe.pas' {frHelpListe: TUniFrame},
  unRptVerbisListeler in 'Raporlar\unRptVerbisListeler.pas' {frRptVerbisListeler: TUniFrame},
  KVKNETAPILib in 'Sistem\KVKNETAPILib.pas',
  unRptVerbisListelerDegisiklikler in 'Raporlar\unRptVerbisListelerDegisiklikler.pas' {frRptVerbisListelerDegisiklikler: TUniFrame},
  unRptErisimYetkiLog in 'Raporlar\unRptErisimYetkiLog.pas' {RptErisimYetkiLog: TUniForm},
  unKullaniciTanimTopluIslem in 'Kurumsal\unKullaniciTanimTopluIslem.pas' {frmKullaniciTanimTopluIslem: TUniForm},
  unRptEnvanterLog in 'Raporlar\unRptEnvanterLog.pas' {RptEnvanterLog: TUniForm},
  unRptSMSLog in 'Raporlar\unRptSMSLog.pas' {RptSMSLog: TUniForm},
  unRptTimeStampLog in 'Raporlar\unRptTimeStampLog.pas' {RptTimeStampLog: TUniForm},
  unRptLoginLog in 'Raporlar\unRptLoginLog.pas' {RptLoginLog: TUniForm},
  unAcikRizaKayitTopluIslem in 'Formlar\unAcikRizaKayitTopluIslem.pas' {frmAcikRizaKayitTopluIslem: TUniForm},
  unRptChecklistLog in 'Raporlar\unRptChecklistLog.pas' {RptChecklistLog: TUniForm},
  unAcikRizaKayitTopluMesaj in 'Formlar\unAcikRizaKayitTopluMesaj.pas' {frmAcikRizaKayitTopluMesaj: TUniForm},
  unRptVeriPaylasimRaporu in 'Raporlar\unRptVeriPaylasimRaporu.pas' {frRptVeriPaylasimRaporu: TUniFrame},
  unFonksiyonSec in 'Kurumsal\unFonksiyonSec.pas' {frmFonksiyonSec: TUniForm},
  unFonksiyonTanim in 'EDanisman\unFonksiyonTanim.pas' {frmFonksiyonTanim: TUniForm},
  unEDanismanCevapTanim in 'EDanisman\unEDanismanCevapTanim.pas' {frmEDanismanCevapTanim: TUniForm},
  unEDanismanSecenekTanim in 'EDanisman\unEDanismanSecenekTanim.pas' {frmEDanismanSecenekTanim: TUniForm},
  unEDanismanSoruListe in 'EDanisman\unEDanismanSoruListe.pas' {frmEDanismanSoruListe: TUniFrame},
  unEDanismanSoruSec in 'EDanisman\unEDanismanSoruSec.pas' {frmEDanismanSoruSec: TUniForm},
  unEDanismanSoruSetiListe in 'EDanisman\unEDanismanSoruSetiListe.pas' {frmEDanismanSoruSetiListe: TUniFrame},
  unEDanismanSoruSetiTanim in 'EDanisman\unEDanismanSoruSetiTanim.pas' {frmEDanismanSoruSetiTanim: TUniForm},
  unEDanismanSoruTanim in 'EDanisman\unEDanismanSoruTanim.pas' {frmEDanismanSoruTanim: TUniForm},
  unFonksiyonListe in 'EDanisman\unFonksiyonListe.pas' {frmFonksiyonListe: TUniFrame},
  unEDanismanSoruSetiCevaplaListe in 'EDanisman\unEDanismanSoruSetiCevaplaListe.pas' {frmEDanismanSoruSetiCevaplaListe: TUniFrame},
  unAydinlatmaSablonTopluIslem in 'Formlar\unAydinlatmaSablonTopluIslem.pas' {frmAydinlatmaSablonTopluIslem: TUniForm},
  DelphiZXIngQRCode in 'Sistem\DelphiZXIngQRCode.pas',
  unEDanismanSoruTopluIslem in 'EDanisman\unEDanismanSoruTopluIslem.pas' {frmEDanismanSoruTopluIslem: TUniForm},
  unKullaniciTanim in 'Kurumsal\unKullaniciTanim.pas' {frmKullaniciTanim: TUniForm},
  JETSMSLib in 'Sistem\JETSMSLib.pas',
  wsJETSMS in 'Sistem\wsJETSMS.pas',
  unDeptUygulamaProseduru in 'Raporlar\unDeptUygulamaProseduru.pas' {frDeptUygulamaProseduru: TUniFrame},
  unKullaniciParolaSifirla in 'Kurumsal\unKullaniciParolaSifirla.pas' {frmKullaniciParolaSifirla: TUniForm},
  unHizliEnvanterGirisi in 'Formlar\unHizliEnvanterGirisi.pas' {frmHizliEnvanterGirisi: TUniForm},
  unEnvanterChecklistTopluIslem in 'Formlar\unEnvanterChecklistTopluIslem.pas' {frmEnvanterChecklistTopluIslem: TUniForm},
  unIKCUSSOLib in 'Sistem\unIKCUSSOLib.pas',
  ActiveDs_TLB in 'Sistem\ActiveDs_TLB.pas',
  adshlp in 'Sistem\adshlp.pas',
  unSurumNot in 'Sistem\unSurumNot.pas' {frmSurumNot: TUniForm},
  ActiveDirectory.Client.Intf in 'Sistem\ActiveDirectory.Client.Intf.pas',
  ActiveDirectory.Client in 'Sistem\ActiveDirectory.Client.pas',
  ActiveDirectory.Client.Winapi in 'Sistem\ActiveDirectory.Client.Winapi.pas',
  ActiveDirectory.Types in 'Sistem\ActiveDirectory.Types.pas',
  ActiveDirectory.Winapi.DllMapper in 'Sistem\ActiveDirectory.Winapi.DllMapper.pas',
  ActiveDirectory.Winapi.TLB in 'Sistem\ActiveDirectory.Winapi.TLB.pas',
  UrlShortLib in 'Sistem\UrlShortLib.pas',
  unkvkkportal in 'Kurumsal\unkvkkportal.pas' {frmkvkkPortal: TUniForm},
  LDAPUtils in 'Sistem\LDAPUtils.pas',
  unVeriTipiAnalizIslemleri in 'Formlar\unVeriTipiAnalizIslemleri.pas' {frmVeriTipiAnalizIslemleri: TUniFrame},
  castutils in 'Sistem\castutils.pas',
  unRiskListeSurec in 'Formlar\unRiskListeSurec.pas' {frRiskLiseSurec: TUniFrame},
  unRiskUtls in 'Formlar\unRiskUtls.pas',
  unRiskSurecTanim in 'Formlar\unRiskSurecTanim.pas' {frmRiskSurecTanim: TUniForm},
  UnRiskEtkiHesaplamaAnketi in 'Formlar\UnRiskEtkiHesaplamaAnketi.pas' {frmRiskEtkiHesaplamaAnketi: TUniForm},
  UnRiskOlasilikHesaplamaAnketi in 'Formlar\UnRiskOlasilikHesaplamaAnketi.pas' {frmRiskOlasilikHesaplamaAnketi: TUniForm},
  UnRiskSurecTedbirTanim in 'Formlar\UnRiskSurecTedbirTanim.pas' {frmRiskSurecTedbirTanim: TUniForm},
  unRiskSurecMevcutDurum in 'Formlar\unRiskSurecMevcutDurum.pas' {frRiskSurecMevcutDurum: TUniFrame},
  UnRiskGozdengecirmeListe in 'Formlar\UnRiskGozdengecirmeListe.pas' {frmRiskGozdengecirmeListe: TUniForm},
  unRiskSurecAnilizHesapInfo in 'Formlar\unRiskSurecAnilizHesapInfo.pas' {FrmRiskHesapInfo: TUniForm},
  UnRiskTanim in 'Tanimlar\UnRiskTanim.pas' {frmRiskTanim: TUniForm},
  UriskListe in 'Kurumsal\UriskListe.pas' {frmRistListe: TUniFrame},
  UnRiskSec in 'Kurumsal\UnRiskSec.pas' {frmRiskSec: TUniForm},
  UnIhlalOlayiTanim in 'Formlar\UnIhlalOlayiTanim.pas' {frmIhlalOlayi: TUniForm},
  unIhlalOlayiListe in 'Formlar\unIhlalOlayiListe.pas' {frmIhlalOlayiListe: TUniFrame},
  unIhlalOlayDetayListe in 'Formlar\unIhlalOlayDetayListe.pas' {frmIhlalOlayDetayListe: TUniFrame},
  unIhlalOlayiBildirimListe in 'Formlar\unIhlalOlayiBildirimListe.pas' {frmIhlalOlayiBildirimListe: TUniFrame},
  UnIhlalOlayiBildirimTanim in 'Formlar\UnIhlalOlayiBildirimTanim.pas' {frmIhlalOlayiBildirimTanim: TUniForm},
  unSecimForm in 'Sistem\unSecimForm.pas' {frmSecimForm: TUniForm},
  unAydinlatmaSablonAcikRizaGereklilik in 'Formlar\unAydinlatmaSablonAcikRizaGereklilik.pas' {frmAydinlatmaSablonAcikRizaGereklilik: TUniForm},
  unLogKullaniciTanim in 'Loglar\unLogKullaniciTanim.pas' {frmLogKullaniciTanim: TUniForm},
  unLogAcikRizaTanim in 'Loglar\unLogAcikRizaTanim.pas' {frmLogAcikRizaTanim: TUniForm},
  unLogVSBasvuruTanim in 'Loglar\unLogVSBasvuruTanim.pas' {frmLogVSBasvuruTanim: TUniForm},
  uAydinlatmaSablonOlusturma in 'Sistem\uAydinlatmaSablonOlusturma.pas' {frmAydinlatmaSablonOlusturma: TUniForm},
  unPDFForm in 'Sistem\unPDFForm.pas' {frmPDFForm: TUniForm},
  UmarmaraLdap in 'Kurumsal\UmarmaraLdap.pas',
  unMailUtils in 'Sistem\unMailUtils.pas' {/  ,},
  unTwoFactorAuth in 'Sistem\unTwoFactorAuth.pas',
  unTwoFAInputForm in 'Sistem\unTwoFAInputForm.pas' {frmTwoFAInput: TUniForm},
  Base32U in 'Sistem\Base32U.pas',
  GoogleOTP in 'Sistem\GoogleOTP.pas',
  unEnvanterTanim2test in 'Formlar\unEnvanterTanim2test.pas' {frmEnvanterTanim2test: TUniForm},
  unSQLLog in 'Formlar\unSQLLog.pas' {frmSQLLog: TUniForm},
  unSysAyarlarListe in 'Kurumsal\unSysAyarlarListe.pas' {frSYSAyarlarListe: TUniFrame},
  unSYSAyarlar in 'Kurumsal\unSYSAyarlar.pas' {frmsysAyarlarTanim: TUniForm},
  unIDMAPPService in 'Kurumsal\unIDMAPPService.pas',
  unPortalSetting in 'Kurumsal\unPortalSetting.pas' {frmPortalSetting: TUniForm};

{$R *.res}

begin
  ReportMemoryLeaksOnShutdown := false;  //True;
  Application.Initialize;
  TServerMod.Create(Application);
  Application.Run;
end.
